# Generated by Django 5.1.6 on 2025-03-11 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedWork',
            fields=[
                ('recommended_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.IntegerField()),
                ('recommended_model', models.CharField(max_length=50)),
                ('recommended_date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.IntegerField(blank=True, null=True)),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
